config/routes.rb
Rails.application.routes.draw do
  resources :student_registrations
  resources :faculty_profiles
  resources :student_profiles
  resources :courses
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :users, only: [:index, :edit, :update]
      root to: 'dashboard#index'
    end
  end

  namespace :student do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/update_profile', to: 'dashboard#update_profile'
    get 'dashboard/course_registration', to: 'dashboard#course_registration', as: 'course_registration'
    get 'dashboard/show_courses', to: 'dashboard#show_courses', as: 'show_courses'
    post 'students/dashboard/course_registration/create_course_registration', to: 'students#dashboard#course_registration#create_course_registration', as: 'create_course_registration'
  end

  namespace :faculty do
    get 'dashboard', to: 'dashboard#index'
  end

  resources :courses, only: [:new, :create]
  # resources :registrations, only: [:new, :destroy]

  root to: redirect('/users/sign_in')
end

app/models/faculty_profile.rb
class FacultyProfile < ApplicationRecord
	belongs_to :user
	has_many :courses
	validates_uniqueness_of :id
end

app/controllers/faculty_profiles_controller.rb
class FacultyProfilesController < ApplicationController
  before_action :set_faculty_profile, only: %i[ show edit update destroy ]

  # GET /faculty_profiles or /faculty_profiles.json
  def index
    @faculty_profiles = FacultyProfile.all
  end

  # GET /faculty_profiles/1 or /faculty_profiles/1.json
  def show
  end

  # GET /faculty_profiles/new
  def new
    @faculty_profile = FacultyProfile.new
  end

  # GET /faculty_profiles/1/edit
  def edit
  end

  # POST /faculty_profiles or /faculty_profiles.json
  def create
    @faculty_profile = FacultyProfile.new(faculty_profile_params.merge(user_id: current_user.id))
    @user = User.new

    respond_to do |format|
      if @faculty_profile.save
        format.html { redirect_to faculty_profile_url(@faculty_profile), notice: "Faculty profile was successfully created." }
        format.json { render :show, status: :created, location: @faculty_profile }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @faculty_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculty_profiles/1 or /faculty_profiles/1.json
  def update
    respond_to do |format|
      if @faculty_profile.update(faculty_profile_params)
        format.html { redirect_to faculty_profile_url(@faculty_profile), notice: "Faculty profile was successfully updated." }
        format.json { render :show, status: :ok, location: @faculty_profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @faculty_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculty_profiles/1 or /faculty_profiles/1.json
  def destroy
    @faculty_profile.destroy!

    respond_to do |format|
      format.html { redirect_to faculty_profiles_url, notice: "Faculty profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty_profile
      @faculty_profile = FacultyProfile.find_by(user_id: current_user.id)
    end

    # Only allow a list of trusted parameters through.
    def faculty_profile_params
      params.require(:faculty_profile).permit(:name, :email_id, :dept, :staff_id, :user_id)
    end
end

app/helpers/faculty_profiles_helper.rb
module FacultyProfilesHelper
end

app/views/faculty_profiles/_faculty_profile.html.erb
<div id="<%= dom_id faculty_profile %>">
 <div class="container mx-auto mt-8">
  <div class="bg-white p-8 rounded-md shadow-md">
    <h2 class="text-3xl font-semibold mb-6">Faculty Details</h2>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <p class="text-gray-700 text-sm">Name:</p>
        <p class="text-lg font-semibold mb-4"><%= @faculty_profile.name %></p>

        <p class="text-gray-700 text-sm">Email:</p>
        <p class="text-lg font-semibold mb-4"><%= @faculty_profile.email_id %></p>
      </div>

      <div>
        <p class="text-gray-700 text-sm">Department:</p>
        <p class="text-lg font-semibold mb-4"><%= @faculty_profile.dept %></p>

        <p class="text-gray-700 text-sm">Roll No:</p>
        <p class="text-lg font-semibold mb-4"><%= @faculty_profile.staff_id %></p>
      </div>
    </div>
    <div class="mt-8">
      <%= link_to 'Edit Profile', edit_faculty_profile_path(@faculty_profile), class: 'bg-blue-500 text-white p-2 rounded-md mr-4' %>
      <%= link_to 'Back to Dashboard', faculty_dashboard_path, class: 'bg-gray-500 text-white p-2 rounded-md' %>
    </div>
  </div>
</div>
</div>

app/views/faculty_profiles/_form.html.erb
<%= form_with(model: faculty_profile) do |form| %>
  <% if faculty_profile.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(faculty_profile.errors.count, "error") %> prohibited this faculty_profile from being saved:</h2>

      <ul>
        <% faculty_profile.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div class="max-w-md mx-auto bg-white p-8 shadow-md rounded-md">
  <h2 class="text-2xl font-semibold mb-6">Faculty Information Form</h2>
    <div>
      <%= form.label :name, class: 'block text-sm font-medium text-gray-700' %>
      <%= form.text_field :name, class: 'mt-1 p-2 border rounded-md w-full' %>
    </div>
    <div>
      <%= form.label :email_id, class: 'block text-sm font-medium text-gray-700' %>
      <%= form.email_field :email_id, class: 'mt-1 p-2 border rounded-md w-full' %>
    </div>
    <div>
      <%= form.label :Department, class: 'block text-sm font-medium text-gray-700' %>
      <%= form.select :dept, options_for_select(['Chemical Engineering', 'Civil Engineering', 'Computer Science Engineering', 'Electrical and Electronics Engineering', 'Electronics and Communication Engineering', 'Information Technology', 'Mathematical and Computational Sciences', 'Mechanical Engineering', 'Metallurgical and Materials Engineering', 'Mining Engineering']), { prompt: 'Select Department' }, class: 'mt-1 p-2 border rounded-md w-full' %>
    </div>
    <div>
      <%= form.label :Staff_ID, class: 'block text-sm font-medium text-gray-700' %>
      <%= form.text_field :staff_id, class: 'mt-1 p-2 border rounded-md w-full' %>
    </div>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <div>
      <%= form.submit 'Submit', class: 'bg-blue-500 text-white p-2 rounded-md w-full' %>
    </div>
  </div>
<% end %>

app/views/faculty_profiles/edit.html.erb
<%= render "form", faculty_profile: @faculty_profile %>

<br>

<div class="max-w-md mx-auto p-8 shadow-md">
  <%= link_to "Show faculty profile", @faculty_profile, class: 'bg-purple-500 text-white p-2 rounded-md w-full' %> 
  <%= link_to "Back to dashboard", faculty_dashboard_path, class: 'bg-green-500 text-white p-2 rounded-md w-full' %>
</div>

app/views/faculty_profiles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Faculty profiles</h1>

<div id="faculty_profiles">
  <% @faculty_profiles.each do |faculty_profile| %>
    <%= render faculty_profile %>
    <p>
      <%= link_to "Show this faculty profile", faculty_profile, class: 'bg-blue-500 text-white p-2 rounded-md w-full' %>
    </p>
  <% end %>
</div>

<%= link_to "New faculty profile", new_faculty_profile_path, class: 'bg-blue-500 text-white p-2 rounded-md w-full' %>

app/views/faculty_profiles/new.html.erb
<%= render "form", faculty_profile: @faculty_profile %>

app/views/faculty_profiles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @faculty_profile %>

<div>

  <%# <%= button_to "Destroy this student profile", @student_profile, method: :delete, class: 'mx-auto bg-red-500 text-white p-2 rounded-md' %>
</div>