config/routes.rb
Rails.application.routes.draw do
  resources :student_registrations
  resources :faculty_profiles
  resources :student_profiles
  resources :courses
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :users, only: [:index, :edit, :update]
      root to: 'dashboard#index'
    end
  end

  namespace :student do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/update_profile', to: 'dashboard#update_profile'
    get 'dashboard/course_registration', to: 'dashboard#course_registration', as: 'course_registration'
    get 'dashboard/show_courses', to: 'dashboard#show_courses', as: 'show_courses'
    post 'students/dashboard/course_registration/create_course_registration', to: 'students#dashboard#course_registration#create_course_registration', as: 'create_course_registration'
  end

  namespace :faculty do
    get 'dashboard', to: 'dashboard#index'
  end

  resources :courses, only: [:new, :create]
  # resources :registrations, only: [:new, :destroy]

  root to: redirect('/users/sign_in')
end

app/models/student_registration.rb
class StudentRegistration < ApplicationRecord
end

app/controllers/student_registrations_controller.rb
class StudentRegistrationsController < ApplicationController
  before_action :set_student_registration, only: %i[ show edit update destroy ]

  # GET /student_registrations or /student_registrations.json
  def index
    @student_registrations = StudentRegistration.all
  end

  # GET /student_registrations/1 or /student_registrations/1.json
  def show
  end

  # GET /student_registrations/new
  def new
    @student_registration = StudentRegistration.new
    @available_courses = Course.where(dept: current_user.student_profile.dept)
  end

  # GET /student_registrations/1/edit
  def edit
  end

  # POST /student_registrations or /student_registrations.json
  def create
    @student_registration = StudentRegistration.new(student_registration_params)

    respond_to do |format|
      if @student_registration.save
        format.html { redirect_to student_registration_url(@student_registration), notice: "Student registration was successfully created." }
        format.json { render :show, status: :created, location: @student_registration }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_registrations/1 or /student_registrations/1.json
  def update
    respond_to do |format|
      if @student_registration.update(student_registration_params)
        format.html { redirect_to student_registration_url(@student_registration), notice: "Student registration was successfully updated." }
        format.json { render :show, status: :ok, location: @student_registration }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student_registration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_registrations/1 or /student_registrations/1.json
  def destroy
    @student_registration.destroy!

    respond_to do |format|
      format.html { redirect_to student_registrations_url, notice: "Student registration was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_registration
      @student_registration = StudentRegistration.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_registration_params
      params.require(:student_registration).permit(:course_code, :student_name)
    end
end

app/helpers/student_registrations_helper.rb
module StudentRegistrationsHelper
end

app/views/student_registrations/_form.html.erb
<%= form_with(model: student_registration) do |form| %>
  <% if student_registration.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student_registration.errors.count, "error") %> prohibited this student_registration from being saved:</h2>

      <ul>
        <% student_registration.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="bg-gray-100 min-h-screen flex items-center justify-center">
  <div class="bg-white p-8 rounded shadow-md w-96">
    <h1 class="text-3xl font-bold mb-6 text-center">Course Registration</h1>
      <div class="mb-4">
        <%= form.label :student_name, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.text_field :student_name, value: current_user.student_profile.name, readonly: true, class: "form-input w-full px-4 py-2 rounded-md border focus:outline-none focus:border-blue-500" %>
      </div>

      <div class="mb-4">
        <%= form.label :course_code, class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= form.select :course_code, @available_courses.map { |course| [course.course_title, course.course_code] }, {}, class: "form-select w-full px-4 py-2 rounded-md border focus:outline-none focus:border-blue-500" %>
      </div>

      <div class="flex items-center justify-center">
        <%= form.submit "Register", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full focus:outline-none focus:shadow-outline-blue active:bg-blue-800" %>
      </div>
  </div>
</div>
<% end %>

app/views/student_registrations/_student_registration.html.erb
<div id="<%= dom_id student_registration %>">
  <div class="bg-gray-100 min-h-screen flex items-center justify-center">
  <div class="bg-white p-8 rounded shadow-md w-96">
    <h1 class="text-3xl font-bold mb-6 text-center">Course Registration Details</h1>

    <div class="mb-4">
      <p class="text-lg font-semibold mb-2">Student Name:</p>
      <p class="text-gray-800"><%= student_registration.student_name %></p>
    </div>

    <div class="mb-4">
      <p class="text-lg font-semibold mb-2">Course Code:</p>
      <p class="text-gray-800"><%= student_registration.course_code %></p>
    </div>
    <%= link_to "Back to dashboard", student_dashboard_path, class: 'bg-green-500 text-white p-2 rounded-md w-full' %>
    <%= link_to "Unregister from course", @student_registration, data: {"turbo-method": :delete }, class: 'bg-green-500 text-white p-2 rounded-md w-full' %>
  </div>
</div>

app/views/student_registrations/edit.html.erb
<h1>Editing student registration</h1>

<%= render "form", student_registration: @student_registration %>

<br>

<div>
  <%= link_to "Show this student registration", @student_registration %> |
  <%= link_to "Back to student registrations", student_registrations_path %>
</div>

app/views/student_registrations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Student registrations</h1>

<div id="student_registrations">
  <% @student_registrations.each do |student_registration| %>
    <%= render student_registration %>
    <p>
      <%= link_to "Show this student registration", student_registration %>
    </p>
  <% end %>
</div>

<%= link_to "New student registration", new_student_registration_path %>

app/views/student_registrations/new.html.erb
<%= render "form", student_registration: @student_registration %>

<br>

<div>
    <%= link_to "Back to dashboard", student_dashboard_path, class: 'bg-green-500 text-white p-2 rounded-md w-full' %>
</div>

app/views/student_registrations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @student_registration %>

<div>
  <%= link_to "Edit this student registration", edit_student_registration_path(@student_registration) %> |
  <%= link_to "Back to student registrations", student_registrations_path %>

  <%= button_to "Destroy this student registration", @student_registration, method: :delete %>
</div>

app/views/student_registrations/show_courses.html.erb
<div class="bg-gray-100 min-h-screen flex items-center justify-center">
  <div class="bg-white p-8 rounded shadow-md w-96">
    <h1 class="text-3xl font-bold mb-6 text-center">Registered Courses</h1>

    <% if @student_registration.courses.any? %>
      <ul class="list-disc list-inside mb-4">
        <% @student_registration.courses.each do |course| %>
          <li class="text-gray-800"><%= course.course_code %></li>
        <% end %>
      </ul>
    <% else %>
      <p class="text-gray-800">You haven't registered for any courses yet.</p>
    <% end %>

    <div class="flex items-center justify-center">
      <%= link_to 'Back to Dashboard', student_dashboard_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full focus:outline-none focus:shadow-outline-blue active:bg-blue-800" %>
    </div>
  </div>
</div>