config/routes.rb
Rails.application.routes.draw do
  resources :student_registrations
  resources :faculty_profiles
  resources :student_profiles
  resources :courses
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :users, only: [:index, :edit, :update]
      root to: 'dashboard#index'
    end
  end

  namespace :student do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/update_profile', to: 'dashboard#update_profile'
    get 'dashboard/course_registration', to: 'dashboard#course_registration', as: 'course_registration'
    get 'dashboard/show_courses', to: 'dashboard#show_courses', as: 'show_courses'
    post 'students/dashboard/course_registration/create_course_registration', to: 'students#dashboard#course_registration#create_course_registration', as: 'create_course_registration'
  end

  namespace :faculty do
    get 'dashboard', to: 'dashboard#index'
  end

  resources :courses, only: [:new, :create]
  # resources :registrations, only: [:new, :destroy]

  root to: redirect('/users/sign_in')
end

app/models/student.rb
class Student < ApplicationRecord
  validates :name, :email_id, :dept, :program, :roll_no, presence: true
  validates :email_id, uniqueness: false
  belongs_to :user
  has_many :registrations
  has_many :courses
  has_one :student_profile
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin_role

  def index
    @users = User.all
  end

  private

  def check_admin_role
    redirect_to root_path, alert: 'Access denied.' unless current_user&.admin?
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  def show
    if current_user.admin?
      redirect_to admin_dashboard
    elsif current_user.student?
      redirect_to student_dashboard
    elsif current_user.faculty?
      redirect_to faculty_dashboard
    else
      redirect_to index_path
    end
  end
end

app/controllers/faculty/dashboard_controller.rb
class Faculty::DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @courses = Course.all
    @new_course = Course.new
    @faculy_profiles = StudentProfile.all
    @faculty_profile = FacultyProfile.find_by(user_id: current_user.id)
    @user = User.new
  end
  def create_course
    @new_course = current_faculty.courses.build(course_params)
    if @new_course.save
      redirect_to faculty_dashboard_path, notice: 'Course created successfully.'
    else
      render :index
    end
  end
  def edit_course
    @course = Course.find(params[:id])
  end
  def update_course
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to faculty_dashboard_path, notice: 'Course updated successfully.'
    else
      render :edit_course
    end
  end
  def destroy_course
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to faculty_dashboard_path, notice: 'Course deleted successfully.'
  end

  private

  def course_params
    params.require(:course).permit(:course_code, :course_title, :instructor, :schedule, :credits, :max_students)
  end
end

app/controllers/student/dashboard_controller.rb
class Student::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @courses = Course.all
    @student_profiles = StudentProfile.all
    @student_profile = StudentProfile.find_by(user_id: current_user.id)
    if current_user.student_profile
      @available_courses = Course.find_by(dept: current_user.student_profile.dept)
      @StudentRegistration = StudentRegistration.where(student_name: current_user.student_profile.name)
      @registered_courses = @StudentRegistration.where(student_name: current_user.student_profile.name)
    end
    @user = User.new
  end

  def show_courses
    @StudentRegistration = StudentRegistration.where(student_name: current_user.student_profile.name)
    @registered_courses = @StudentRegistration.where(student_name: current_user.student_profile.name)
  end

  def course_registration
    @available_courses = Course.where(dept: current_user.student_profile.dept)
  end

  def create_course_registration
    @student = current_user.student_profile
    selected_course_ids = params[:id]

    if @student && selected_course_ids
      @student.courses << Course.find(selected_course_codes)
      redirect_to student_dashboard_path, notice: 'Courses registered successfully!'
    else
      redirect_to student_course_registration_path, alert: 'Failed to register for courses.'
    end
  end

  # def edit_profile
  #   @student = Student.new
  # end

  # def update_profile
  #   # @student = Student.new(student_params)
  #   @student = current_user.student.build(student_params)
  #   if @student.save
  #     redirect_to student_dashboard_path, notice: 'Profile updated successfully.'
  #   else
  #     puts "Validation errors: #{@student.errors.full_messages}"
  #     render :edit_profile
  #   end
  # end

  # def student_params
  #   params.permit(:name, :email_id, :dept, :roll_no, :program, :cgpa, :user_id)
  # end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  before_action :authenticate_user!
  before_action :check_student_role

  def index
    @student = current_user
  end

  private
  def check_student_role
    redirect_to root_path unless current_user.role == 'student'
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/student/dashboard/course_registration.html.erb
<h2>Select Courses</h2>
<%= form_with(url: student_create_course_registration_path, method: :post) do |form| %>
  <% @available_courses.each do |course| %>
    <div>
      <%= check_box_tag 'course_ids[]', course.id %>
      <%= label_tag "course_ids_#{course.course_code}", course.course_title %>
    </div>
  <% end %>

  <%= form.submit 'Register Selected Courses', class: 'btn btn-primary' %>
<% end %>

app/views/student/dashboard/index.html.erb
<div class="container mx-auto mt-8">
  <h1 class="text-4xl font-bold mb-4">Student Dashboard</h1>
  <div class="mb-8">
    <% if StudentProfile.exists?(user_id: current_user.id) %>
      <%= link_to 'Show Profile', @student_profile, class: 'bg-blue-500 text-white p-2 rounded-md w-full' %>
      <%= link_to 'Edit Profile', edit_student_profile_path(current_user.id), class: 'bg-blue-500 text-white p-2 rounded-md w-full' %>
      <%= link_to 'Register for courses', new_student_registration_path, class: 'bg-blue-500 text-white p-2 rounded-md w-full' %>
      <%= link_to 'Show registered courses', student_show_courses_path, class: 'bg-blue-500 text-white p-2 rounded-md w-full' %>
    <% else %>
      <%= link_to 'Create Profile', new_student_profile_path, class: 'bg-blue-500 text-white p-2 rounded-md w-full' %>
    <% end %>
  </div>
  <% if StudentProfile.exists?(user_id: current_user.id) %>
  <div class="mb-8">
  <h2 class="text-2xl font-semibold mb-4">Available Courses</h2>
  <table class="min-w-full bg-white border border-gray-300">
    <thead>
      <tr>
        <th class="py-2 px-4 border-b">Course Title</th>
        <th class="py-2 px-4 border-b">Course Code</th>
        <th class="py-2 px-4 border-b">Instructor</th>
        <th class="py-2 px-4 border-b">Schedule</th>
        <th class="py-2 px-4 border-b">Credits</th>
        <th class="py-2 px-4 border-b">Maximum Number of registrations</th>
        <th class="py-2 px-4 border-b">Remaining seats</th>
      </tr>
    </thead>
    <tbody>
      <% @courses.each do |course| %>
        <% if course.dept == @student_profile.dept %>
          <tr>
            <td class="py-2 px-4 border-b"><%= course.course_title %></td>
            <td class="py-2 px-4 border-b"><%= course.course_code %></td>
            <td class="py-2 px-4 border-b"><%= course.instructor %></td>
            <td class="py-2 px-4 border-b"><%= course.schedule %></td>
            <td class="py-2 px-4 border-b"><%= course.credits %></td>
            <td class="py-2 px-4 border-b"><%= course.max_students %></td>
            <td class="py-2 px-4 border-b"><%= course.max_students - @StudentRegistration.where(course_code: course.course_code).count %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
  <h1 class="text-4xl font-bold mb-4">Please create a profile in order to view the courses</h1>
<% end %>
</div>

app/views/student/dashboard/show_courses.html.erb
<div class="bg-gray-100 min-h-screen flex items-center justify-center">
  <div class="bg-white p-8 rounded shadow-md w-96">
    <h1 class="text-3xl font-bold mb-6 text-center">Registered Courses</h1>

    <% if @registered_courses %>
      <ul class="list-disc list-inside mb-4">
        <% @registered_courses.each do |course| %>
          <li class="text-gray-800"><%= course.course_code %></li>
        <% end %>
      </ul>
    <% else %>
      <p class="text-gray-800">You haven't registered for any courses yet.</p>
    <% end %>

    <div class="flex items-center justify-center">
      <%= link_to 'Back to Dashboard', student_dashboard_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full focus:outline-none focus:shadow-outline-blue active:bg-blue-800" %>
    </div>
  </div>
</div>