config/routes.rb
Rails.application.routes.draw do
  resources :student_registrations
  resources :faculty_profiles
  resources :student_profiles
  resources :courses
  get 'home/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  authenticated :user, lambda { |u| u.admin? } do
    namespace :admin do
      resources :users, only: [:index, :edit, :update]
      root to: 'dashboard#index'
    end
  end

  namespace :student do
    get 'dashboard', to: 'dashboard#index'
    get 'dashboard/update_profile', to: 'dashboard#update_profile'
    get 'dashboard/course_registration', to: 'dashboard#course_registration', as: 'course_registration'
    get 'dashboard/show_courses', to: 'dashboard#show_courses', as: 'show_courses'
    post 'students/dashboard/course_registration/create_course_registration', to: 'students#dashboard#course_registration#create_course_registration', as: 'create_course_registration'
  end

  namespace :faculty do
    get 'dashboard', to: 'dashboard#index'
  end

  resources :courses, only: [:new, :create]
  # resources :registrations, only: [:new, :destroy]

  root to: redirect('/users/sign_in')
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  validates :name, :email_id, :dept, :staff_id, presence: true
  validates :email_id, uniqueness: true
  has_secure_password
  has_many :courses
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin_role

  def index
    @users = User.all
  end

  private

  def check_admin_role
    redirect_to root_path, alert: 'Access denied.' unless current_user&.admin?
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  def show
    if current_user.admin?
      redirect_to admin_dashboard
    elsif current_user.student?
      redirect_to student_dashboard
    elsif current_user.faculty?
      redirect_to faculty_dashboard
    else
      redirect_to index_path
    end
  end
end

app/controllers/faculty/dashboard_controller.rb
class Faculty::DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
    @courses = Course.all
    @new_course = Course.new
    @faculy_profiles = StudentProfile.all
    @faculty_profile = FacultyProfile.find_by(user_id: current_user.id)
    @user = User.new
  end
  def create_course
    @new_course = current_faculty.courses.build(course_params)
    if @new_course.save
      redirect_to faculty_dashboard_path, notice: 'Course created successfully.'
    else
      render :index
    end
  end
  def edit_course
    @course = Course.find(params[:id])
  end
  def update_course
    @course = Course.find(params[:id])
    if @course.update(course_params)
      redirect_to faculty_dashboard_path, notice: 'Course updated successfully.'
    else
      render :edit_course
    end
  end
  def destroy_course
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to faculty_dashboard_path, notice: 'Course deleted successfully.'
  end

  private

  def course_params
    params.require(:course).permit(:course_code, :course_title, :instructor, :schedule, :credits, :max_students)
  end
end

app/controllers/faculty_controller.rb
class FacultyController < ApplicationController
  before_action :authenticate_user!
  before_action :check_faculty_role
  def index

  end

  private
  def check_faculty_role
    redirect_to root_path unless current_user.role == 'faculty'
  end
end

app/controllers/student/dashboard_controller.rb
class Student::DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @courses = Course.all
    @student_profiles = StudentProfile.all
    @student_profile = StudentProfile.find_by(user_id: current_user.id)
    if current_user.student_profile
      @available_courses = Course.find_by(dept: current_user.student_profile.dept)
      @StudentRegistration = StudentRegistration.where(student_name: current_user.student_profile.name)
      @registered_courses = @StudentRegistration.where(student_name: current_user.student_profile.name)
    end
    @user = User.new
  end

  def show_courses
    @StudentRegistration = StudentRegistration.where(student_name: current_user.student_profile.name)
    @registered_courses = @StudentRegistration.where(student_name: current_user.student_profile.name)
  end

  def course_registration
    @available_courses = Course.where(dept: current_user.student_profile.dept)
  end

  def create_course_registration
    @student = current_user.student_profile
    selected_course_ids = params[:id]

    if @student && selected_course_ids
      @student.courses << Course.find(selected_course_codes)
      redirect_to student_dashboard_path, notice: 'Courses registered successfully!'
    else
      redirect_to student_course_registration_path, alert: 'Failed to register for courses.'
    end
  end

  # def edit_profile
  #   @student = Student.new
  # end

  # def update_profile
  #   # @student = Student.new(student_params)
  #   @student = current_user.student.build(student_params)
  #   if @student.save
  #     redirect_to student_dashboard_path, notice: 'Profile updated successfully.'
  #   else
  #     puts "Validation errors: #{@student.errors.full_messages}"
  #     render :edit_profile
  #   end
  # end

  # def student_params
  #   params.permit(:name, :email_id, :dept, :roll_no, :program, :cgpa, :user_id)
  # end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/faculty_helper.rb
module FacultyHelper
end

app/views/faculty/dashboard/index.html.erb
<div class="container mx-auto mt-8">
  <h1 class="text-4xl font-bold mb-4">Faculty Dashboard</h1>
  <div>
     <% if FacultyProfile.exists?(user_id: current_user.id) %>
      <%= link_to 'Show Profile', @faculty_profile, class: 'bg-blue-500 text-white p-2 rounded-md w-full' %>
      <%= link_to 'Edit Profile', edit_faculty_profile_path(current_user.id), class: 'bg-blue-500 text-white p-2 rounded-md w-full' %>
      <%= link_to 'Create Course', new_course_path, class: 'bg-green-500 text-white p-2 rounded-md w-full' %>
    <% else %>
      <%= link_to 'Create Profile', new_faculty_profile_path, class: 'bg-blue-500 text-white p-2 rounded-md w-full' %>
    <% end %>
  </div>
  <br>
  <% if FacultyProfile.exists?(user_id: current_user.id) %>
  <div class="mb-8">
  <h2 class="text-2xl font-semibold mb-4">Courses</h2>
  <table class="min-w-full bg-white border border-gray-300">
    <thead>
      <tr>
        <th class="py-2 px-4 border-b">Course Title</th>
        <th class="py-2 px-4 border-b">Course Code</th>
        <th class="py-2 px-4 border-b">Instructor</th>
        <th class="py-2 px-4 border-b">Schedule</th>
        <th class="py-2 px-4 border-b">Credits</th>
        <th class="py-2 px-4 border-b">Maximum Number of registrations</th>
        <th class="py-2 px-4 border-b">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @courses.each do |course| %>
        <% if course.dept == @faculty_profile.dept && course.user_id == @faculty_profile.user_id %>
          <tr>
            <td class="py-2 px-4 border-b"><%= course.course_title %></td>
            <td class="py-2 px-4 border-b"><%= course.course_code %></td>
            <td class="py-2 px-4 border-b"><%= course.instructor %></td>
            <td class="py-2 px-4 border-b"><%= course.schedule %></td>
            <td class="py-2 px-4 border-b"><%= course.credits %></td>
            <td class="py-2 px-4 border-b"><%= course.max_students %></td>
            <td class="py-2 px-4 border-b">
              <%= link_to 'Show', course, class: 'text-blue-500 mr-2' %>
              <%= link_to 'Edit', edit_course_path(course), class: 'text-green-500 mr-2' %>
              <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'text-red-500' %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>
<% else %>
 <h1 class="text-4xl font-bold mb-4">Please create a profile in order to create and view courses</h1>
 <% end %>
</div>